import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { ActiveThemeProvider } from "@/components/theme/active-theme";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const cookieStore = await cookies();
	const activeThemeValue = cookieStore.get("active_theme")?.value;

	return (
		<html lang="zh" suppressHydrationWarning>
			<body
				className={cn(
					`${geist.variable}`,
					"antialiased",
					activeThemeValue ? `theme-${activeThemeValue}` : "",
				)}
			>
				<ThemeProvider attribute="class" disableTransitionOnChange enableSystem>
					<ActiveThemeProvider initialTheme={activeThemeValue}>
						{children}
					</ActiveThemeProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
