import "@/styles/globals.css";

import type { Metadata } from "next";
import {
	Libre_Baskerville,
	Merriweather,
	Plus_Jakarta_Sans,
	Poppins,
	Quicksand,
} from "next/font/google";

import { ActiveThemeProvider } from "@/components/theme/active-theme";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const merriweather = Merriweather({
	weight: "400",
	subsets: ["latin"],
	variable: "--font-merriweather",
});

const quicksand = Quicksand({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-quicksand",
});

const poppins = Poppins({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-poppins",
});

const libreBaskerville = Libre_Baskerville({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-libre-baskerville",
});

const plusJakartaSans = Plus_Jakarta_Sans({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-libre-plus-jakarta-sans",
});

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const cookieStore = await cookies();
	const activeThemeValue = cookieStore.get("active_theme")?.value;

	return (
		<html lang="zh" suppressHydrationWarning>
			<body
				className={cn(
					`${merriweather.variable}`,
					`${quicksand.variable}`,
					`${poppins.variable}`,
					`${libreBaskerville.variable}`,
					`${plusJakartaSans.variable}`,
					"antialiased",
					activeThemeValue ? `theme-${activeThemeValue}` : "",
				)}
			>
				<ThemeProvider attribute="class" disableTransitionOnChange enableSystem>
					<ActiveThemeProvider initialTheme={activeThemeValue}>
						{children}
					</ActiveThemeProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
